### ISSUE TITLE
Vivado gets stuck on  git commit

### ISSUE THREAD

**Issue by rafaelnp** [barbedo/vivado-git#10]
I followed the instructions on the [README](https://github.com/barbedo/vivado-git/blob/master/README.md) file, and when the command `git commit` is executed on the Tcl console, VIvado gets stuck (see image below), even tough the Tcl script is generate and can afterwards recreate the project.  

![image](https://user-images.githubusercontent.com/1737706/127292223-0707590a-1bde-4cfe-a0f4-c8e49331a4cc.png)

After clicking on cancel, nothing changes. I am using:
*  Vivado 2020.2
* Arch Linux 5.13.5-arch1-1

Would you have any hints on how to avoid/fix or debug it?

Thanks.

**Comment by Readon** [comment]
git commit -am "xxxxxx"

**Comment by barbedo** [comment]
Hey,

Yup, this happens because you probably have a terminal-based editor as the default for commit messages, and the Tcl Console on Vivado cannot handle it.

On 021a482, I added an error message to the scripts if you try to call `git commit` without the `-m` flag. Ugly, but I can't think of a better solution right now.
I also added a note to the README file.

Feel free to reopen the issue if the problem still happens.
