### ISSUE TITLE
Write project with blockdesign, use_bd_files and no_copy_sources option

### ISSUE THREAD

**Issue by mschreng** [barbedo/vivado-git#6]
After copying the related files into the src folder and modifying the resulting myproject.tcl, i could generate a project from this without errors. The modfications were:

- change file paths to point to the files in src/
- replacing 
`set imported_files [import_files -fileset sources_1 $files]`  with
 `add_files -norecurse -fileset $obj $files` (= option "no_copy_sources").
- added  `set file [file normalize $file]` after file definitons, but i am not sure this was necessary.

When using `git commit` on a project with a blockdesign, the newly written project_name.tcl file does not contain the steps to directly regenerate the blockdesign part. Instead, the tcl file refers to a *.bd file (due to the option -use_bd_files). 
However, the file *.bd is in the `vivado_project` directory, which is excluded from the git repository.
I removed the -use_bd_files option for the git commit command, but the script throws the error:
"This design contains BD sources. The option -no_copy_sources cannot be used without -use_bd_files.  Please remove -no_copy_sources if you wish to write out BD's as procs in the project tcl, otherwise add the option -use_bd_files to directly include the *.bd files to the new project"

My questions:
- Why does the script prevent the usage of the "no_copy_sources" option? 
- Could you elaborate a bit on the reason for relying on the *.bd file instead of recreating everything within the tcl script. I have seen many projects that were archived using the latter approach, can i somehow use this instead? 
- As the bd directory is comparably large, which other files (e.g.  .bxml) have to be included under `src/bd` and how to split the bd directory into 
-- `src/bd ` (version control)
-- `vivado_project/ ,srcs/sources_1/bd/ /` (generated) ?

**Comment by barbedo** [comment]
Hey!

(Better late then never.)

I agree completely that the BD handling is bad.
By default, the original `write_project_tcl` will create a BD generator script instead of using the `.bd` files, but it will refuse to do so with the `-no_copy_sources` option.

I don't really get the rationale of this filter in the original Xilinx script, so I just added `-use_bd_files` as a knee-jerk reaction to #2.
Since I was not using block designs, I didn't think too much about the effects of using this option.

I tried do remedy this in b87abb1f42330026ab7e5306ad91361396dbf16a by changing a little bit the behavior of `write_project_tcl_git.tcl`:

- Remove `-use_bd_files` from the wrapper (in `git commit` and  `wproj`).
- Remove check for `-no_copy_sources` and  `-use_bd_files` being used together.
- Skip the block design(s) wrapper file(s) when generating the list of sources.
- Add automatic wrapper generation for each block design.

One constraint after these changes is that every wrapper file to a block design **must** be called `${block_design_filename}_wrapper`, which seems to be the default when creating them using the Vivado GUI.

Another constraint is that the generated wrapper should not be source controlled anymore. That means that you cannot change the wrapper by hand. If you need to make changes, you can make a handwritten wrapper to the generated wrapper and put that under source control.

If you are still interested, you can check the the latest commit and see if it works for you.

**Comment by barbedo** [comment]
This should be fixed in the latest commits.

Feel free to reopen this issue if you have more questions.
